services:
  n8n:
    stdin_open: true
    tty: true
    # ports:
    #   - 8084:5678
    environment:
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_RUNNERS_ENABLED: true
      N8N_SECURE_COOKIE: false
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_DATABASE=<POSTGRES_DATABASE> \
      # - DB_POSTGRESDB_HOST=<POSTGRES_HOST> \
      # - DB_POSTGRESDB_PORT=<POSTGRES_PORT> \
      # - DB_POSTGRESDB_USER=<POSTGRES_USER> \
      # - DB_POSTGRESDB_SCHEMA=<POSTGRES_SCHEMA> \
      # - DB_POSTGRESDB_PASSWORD=<POSTGRES_PASSWORD> \
    volumes:
      - n8n_dir:/home/node/.n8n
    image: docker.n8n.io/n8nio/n8n