services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    #container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8086
      - TORRENTING_PORT=6881
    volumes:
      #- qbittorrent_config:/config
      - qbittorrent_dir:/downloads #optional
    ports:
      - 8086:8086
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped