## traefik.yml




# Docker configuration backend
providers:
  docker:
    #defaultRule: "PathPrefix(`/services/{{ trimPrefix `/` .Name }}`)"
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"


# API and dashboard configuration
api:
  insecure: true
